### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by sisrfeng** [lars76/kmeans-anchor-boxes#16]
你好，我运行后没有输出，请问是为什么呢？

asus@asus:~/c001/VOC2007/kmeans-anchor-boxes-master$ python3 -m unittest discover -s tests/
............FF
FAIL: test_kmeans_5 (test_voc2007.TestVoc2007)
Traceback (most recent call last):
File "/home/luvision/c001/VOC2007/kmeans-anchor-boxes-master/tests/test_voc2007.py", line 37, in test_kmeans_5
np.testing.assert_almost_equal(percentage, 0.61, decimal=2)
File "/home/luvision/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 581, in assert_almost_equal
raise AssertionError(_build_err_msg())
AssertionError:
Arrays are not almost equal to 2 decimals
ACTUAL: 0.8394690411933133
DESIRED: 0.61

======================================================================
FAIL: test_kmeans_9 (test_voc2007.TestVoc2007)
Traceback (most recent call last):
File "/home/luvision/c001/VOC2007/kmeans-anchor-boxes-master/tests/test_voc2007.py", line 45, in test_kmeans_9
np.testing.assert_almost_equal(percentage, 0.672, decimal=2)
File "/home/luvision/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 581, in assert_almost_equal
raise AssertionError(_build_err_msg())
AssertionError:
Arrays are not almost equal to 2 decimals
ACTUAL: 0.8947800941384673
DESIRED: 0.672

Ran 14 tests in 5.298s

FAILED (failures=2)

如果去掉tests/test_voc2007.py这两行：
np.testing.assert_almost_equal(percentage, 0.61, decimal=2)
np.testing.assert_almost_equal(percentage, 0.672, decimal=2)

就是这样
asus@asus:~/c001/VOC2007/kmeans-anchor-boxes-master$ python3 -m unittest discover -s tests/
..............jiji
Ran 14 tests in 3.390s

OK

**Comment by sisrfeng** [comment]
Just use example.py and you should be fine.
